config/routes.rb
Rails.application.routes.draw do
  resources :feedback_comments
  resources :employees
  namespace :visitors do
  	get :index
  end
  root :to => "visitors#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
	
	has_many :feedback_comments

	#cocoon
	accepts_nested_attributes_for :feedback_comments, reject_if: :all_blank
	
	#paperclip
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

end

app/models/feedback_comment.rb
class FeedbackComment < ApplicationRecord
  belongs_to :employee
  #enum
  enum type: [:comments, :questions]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to root_path, notice: 'Feedback Sent successfully.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: '' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :designation, :email, :phone_number, feedback_comments_attributes: [:id, :type, :description, :regarding_field, :_destroy])
    end
end

app/controllers/feedback_comments_controller.rb
class FeedbackCommentsController < ApplicationController
  before_action :set_feedback_comment, only: [:show, :edit, :update, :destroy]

  # GET /feedback_comments
  # GET /feedback_comments.json
  def index
    @feedback_comments = FeedbackComment.all
  end

  # GET /feedback_comments/1
  # GET /feedback_comments/1.json
  def show
  end

  # GET /feedback_comments/new
  def new
    @feedback_comment = FeedbackComment.new
  end

  # GET /feedback_comments/1/edit
  def edit
  end

  # POST /feedback_comments
  # POST /feedback_comments.json
  def create
    @feedback_comment = FeedbackComment.new(feedback_comment_params)

    respond_to do |format|
      if @feedback_comment.save
        format.html { redirect_to @feedback_comment, notice: 'Feedback comment was successfully created.' }
        format.json { render :show, status: :created, location: @feedback_comment }
      else
        format.html { render :new }
        format.json { render json: @feedback_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedback_comments/1
  # PATCH/PUT /feedback_comments/1.json
  def update
    respond_to do |format|
      if @feedback_comment.update(feedback_comment_params)
        format.html { redirect_to @feedback_comment, notice: 'Feedback comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @feedback_comment }
      else
        format.html { render :edit }
        format.json { render json: @feedback_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedback_comments/1
  # DELETE /feedback_comments/1.json
  def destroy
    @feedback_comment.destroy
    respond_to do |format|
      format.html { redirect_to feedback_comments_url, notice: 'Feedback comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback_comment
      @feedback_comment = FeedbackComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_comment_params
      params.require(:feedback_comment).permit(:feedback_type, :feedback_description, :regarding_field, :employee_id)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
	def index
		
	end
	def feedback_form
		
	end
end	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/feedback_comments_helper.rb
module FeedbackCommentsHelper
end

app/views/employees/_feedback_comment_fields.html.slim
.nested-fields
	.form-inputs.col-md-6.pb-20px.pl-240px
		label FeedBack Regarding 
		= f.input :regarding_field,label: false, input_html: {class: "txt-box-style"}
	.form-inputs.col-md-6.pb-20px
		label Feedback Type
		= f.input :type,label: false,as: :select, collection: [['Comments'], ['Questions']], input_html: {class: "txt-box-style bg-white"}
	.form-inputs.col-md-12.pb-20px.pl-240px 
		label Description Feedback*
		= f.input :description,label: false, as: :text, autofocus: true, :input_html => {:style => 'width: 70%', :rows => 5, class: "description-box"}
	.col-md-12.pb-20px.pl-240px
		= link_to_remove_association "Remove FeedBack", f, class:"btn btn-warning", id:"remove-btn"

app/views/employees/_form.html.slim
.background-color-wt
	.feedback-banner
		.content-head
			h1 Feed Back
		.content-quote	
			h3 We all need people who will give us feedback. That's how we improve.
	.pt-70px.container
		= simple_form_for(@employee) do |f|
		  = f.error_notification
		  .div
			  .form-inputs.col-md-6.pb-20px.pl-240px
			  	label First Name
			  	= f.input :first_name,label: false, input_html: {class: "txt-box-style"}
			  .form-inputs.col-md-6.pb-20px
			  	label Last Name
			  	= f.input :last_name,label: false, input_html: {class: "txt-box-style"}
			  .form-inputs.col-md-6.col-xs-6.pb-20px.pl-240px
			  	label Designation
			    = f.input :designation,label: false, input_html: {class: "txt-box-style"}
			  .form-inputs.col-md-6.pb-20px 
			  	label Email
			    = f.input :email,label: false, input_html: {class: "txt-box-style"}
			  .form-inputs.col-md-12.pb-20px.pl-240px
			  	label Contact Number 
			    = f.input :phone_number,label: false, input_html: {class: "txt-box-style"}
			  .div    
					h4.pt-50px.pl-240px Click 'Add Feedback' Button For Your Feedback's
					#feedback_comment
						= f.simple_fields_for :feedback_comments do |feedback_comment|
							= render 'feedback_comment_fields', f: feedback_comment
						.links.col-md-6.pb-20px.pl-240px
							= link_to_add_association 'Add Feedback', f, :feedback_comments, class: "btn btn-info"
					.col-md-12.pb-20px.pl-240px
						= f.button :submit, 'Submit Form !', class: "btn btn-primary btn-lg", id:"feedback_submit"
						   

app/views/employees/edit.html.slim
h1 Editing employee

== render 'form'

=> link_to 'Show', @employee
'|
=< link_to 'Back', employees_path

app/views/employees/index.html.slim
h1 Listing employees

table
  thead
    tr
      th
      th
      th

  tbody
    - @employees.each do |employee|
      tr
        td = link_to 'Show', employee
        td = link_to 'Edit', edit_employee_path(employee)
        td = link_to 'Destroy', employee, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Employee', new_employee_path

app/views/employees/new.html.slim
== render 'form'

/ = link_to 'Back', employees_path

app/views/employees/show.html.slim
p#notice = notice


=> link_to 'Edit', edit_employee_path(@employee)
'|
=< link_to 'Back', employees_path

app/views/feedback_comments/_form.html.slim
= simple_form_for(@feedback_comment) do |f|
  = f.error_notification

  .form-inputs
    = f.input :feedback_type
    = f.input :feedback_description
    = f.input :regarding_field
    = f.association :Employee

  .form-actions
    = f.button :submit

app/views/feedback_comments/edit.html.slim
h1 Editing feedback_comment

== render 'form'

=> link_to 'Show', @feedback_comment
'|
=< link_to 'Back', feedback_comments_path

app/views/feedback_comments/index.html.slim
h1 Listing feedback_comments

table
  thead
    tr
      th Feedback type
      th Feedback description
      th Regarding field
      th Employee
      th
      th
      th

  tbody
    - @feedback_comments.each do |feedback_comment|
      tr
        td = feedback_comment.feedback_type
        td = feedback_comment.feedback_description
        td = feedback_comment.regarding_field
        td = feedback_comment.Employee
        td = link_to 'Show', feedback_comment
        td = link_to 'Edit', edit_feedback_comment_path(feedback_comment)
        td = link_to 'Destroy', feedback_comment, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Feedback comment', new_feedback_comment_path

app/views/feedback_comments/new.html.slim
h1 New feedback_comment

== render 'form'

= link_to 'Back', feedback_comments_path

app/views/feedback_comments/show.html.slim
p#notice = notice

p
  strong Feedback type:
  = @feedback_comment.feedback_type
p
  strong Feedback description:
  = @feedback_comment.feedback_description
p
  strong Regarding field:
  = @feedback_comment.regarding_field
p
  strong Employee:
  = @feedback_comment.Employee

=> link_to 'Edit', edit_feedback_comment_path(@feedback_comment)
'|
=< link_to 'Back', feedback_comments_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Feedback</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/visitors/index.html.slim
.background-color
	.banner
		.welcome-user-name
			h1 Hi, @user name
		.date-time	
			h1 #{DateTime.now.strftime("%A, %d %b %Y %l:%M %p")}
		.home-feedbtn
			= link_to 'For FeedBack',  new_employee_path,  class: "btn btn-primary btn-lg btn-font"